version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-crafty-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}                # <-- mettilo in Portainer (NON su GitHub)
      CRAFTY_CONTAINER: ${CRAFTY_CONTAINER:-big-bear-crafty}
      ALLOWED_CHANNEL_ID: ${ALLOWED_CHANNEL_ID:-1420794687714754712}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
