version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discordbot-discord-bot-1
    restart: unless-stopped
    environment:
     environment:
  - DISCORD_TOKEN=${DISCORD_TOKEN}
  - CRAFTY_CONTAINER=big-bear-crafty
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
