version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-crafty-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      CRAFTY_CONTAINER: ${CRAFTY_CONTAINER:-big-bear-crafty}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["node", "index.js"]
