version: "3.8"

services:
  discord-bot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CRAFTY_CONTAINER_NAME=big-bear-crafty   # <-- dal tuo screenshot è questo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
