version: "3.8"

services:
  discord-bot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - GUILD_ID=${GUILD_ID}
      - CRAFTY_CONTAINER_NAME=big-bear-crafty
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
