version: "3.8"

services:
  discord-bot:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: ["node", "index.js"]
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_APP_ID=${DISCORD_APP_ID}
      - GUILD_ID=${GUILD_ID}
      - CRAFTY_URL=${CRAFTY_URL}
      - CRAFTY_API_KEY=${CRAFTY_API_KEY}
      - CRAFTY_SERVER_ID=${CRAFTY_SERVER_ID}
      - CRAFTY_INSECURE=1
