version: "3.8"

services:
  discord-bot:
    build: .
    container_name: discord-crafty-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}            # <-- metti in Portainer (mai su GitHub)
      DISCORD_APP_ID: ${DISCORD_APP_ID}          # Application ID
      GUILD_ID: ${GUILD_ID}                      # ID del tuo server Discord
      CRAFTY_CONTAINER: ${CRAFTY_CONTAINER:-big-bear-crafty}
      ALLOWED_CHANNEL_ID: ${ALLOWED_CHANNEL_ID:-1420794687714754712}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
