version: "3.8"
services:
  discord-bot:
    build: .
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - CRAFTY_URL=${CRAFTY_URL}
      - CRAFTY_INSECURE=${CRAFTY_INSECURE:-1}     # 1 = accetta certificato self-signed
      - CRAFTY_USER=${CRAFTY_USER}
      - CRAFTY_PASSWORD=${CRAFTY_PASSWORD}
      - CRAFTY_SERVER_ID=${CRAFTY_SERVER_ID}
    restart: unless-stopped
